"""
Author: Ugur AtesMarkdown report generator."""

from typing import Dict
from datetime import datetime
import logging

logger = logging.getLogger(__name__)
class MarkdownReportGenerator:
    """Generate Markdown reports."""
    
    @staticmethod
    def generate_ioc_report(analysis_result: Dict) -> str:
        """
        Generate Markdown report for IOC investigation.
        
        Args:
            analysis_result: IOC analysis results
        
        Returns:
            Markdown report string
        """
        ioc = analysis_result.get('ioc', 'N/A')
        ioc_type = analysis_result.get('ioc_type', 'N/A')
        threat_score = analysis_result.get('threat_score', 0)
        verdict = analysis_result.get('verdict', 'UNKNOWN')
        
        md = f"""# 🛡️ IOC Investigation Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 📊 Verdict

**{verdict}** - Threat Score: **{threat_score}/100**

---

## 📋 IOC Information

- **Indicator:** `{ioc}`
- **Type:** {ioc_type.upper()}
- **Sources Checked:** {analysis_result.get('sources_checked', 0)}
- **Detections:** {analysis_result.get('sources_flagged', 0)}

---

## 🔍 Threat Intelligence Results

| Source | Status | Details |
|--------|--------|---------|
"""
        
        # Add source results
        sources = analysis_result.get('sources', {})
        for source_name, source_data in sources.items():
            status = source_data.get('status', '⚠')
            details = []
            
            if 'detections' in source_data:
                details.append(f"Detections: {source_data['detections']}")
            if 'confidence' in source_data:
                details.append(f"Confidence: {source_data['confidence']}%")
            if 'botnet' in source_data:
                details.append(f"Botnet: {source_data['botnet']}")
            if 'error' in source_data:
                details.append(f"Error: {source_data['error']}")
            
            details_str = ', '.join(details) if details else 'N/A'
            
            md += f"| {source_name.replace('_', ' ').title()} | {status} | {details_str} |\n"
        
        # Add recommendations
        recommendations = analysis_result.get('recommendations', [])
        if recommendations:
            md += "\n---\n\n## 💡 Recommendations\n\n"
            for rec in recommendations:
                md += f"- {rec}\n"
        
        md += "\n---\n\n*Generated by Blue Team Assistant*\n"
        
        return md
    
    @staticmethod
    def save_report(md_content: str, output_path: str):
        """
        Save Markdown report to file.
        
        Args:
            md_content: Markdown string
            output_path: Output file path
        """
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(md_content)
            logger.info(f"[REPORT] Saved Markdown report: {output_path}")
        except Exception as e:
            logger.error(f"[REPORT] Failed to save report: {e}")
